name: Upload to GitHub Pages

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: erlef/setup-beam@v1
        with:
          otp-version: "26.0.2"
          gleam-version: "0.34.1"
          rebar3-version: "3"
          # elixir-version: "1.15.4"
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - run: gleam deps download
      - run: gleam docs build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          personal_token: ${{ secrets.PERSONAL_TOKEN }}
          publish_dir: ./build/dev/docs/mroew
